"use strict";
exports.__esModule = true;
// let message = "welcome back";
// console.log(message);
var isBeginner = true;
var total = 1000;
var name = 'Alice';
var sentence = "My names is " + name + "\n    I am a beginner in TypeScript";
console.log(sentence);
var n = null;
var u = undefined;
var list1 = [1, 2, 3];
var list2 = [1, 2, 3];
var person1 = ['Tom', 55];
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Blue"] = 2] = "Blue";
})(Color || (Color = {}));
;
var c = Color.Green;
console.log(c);
var randomValue = 10;
randomValue = 'Tom';
randomValue = true;
